import { useEffect, useState } from "react";
import { useNavigate } from "react-router-dom";
import { useAppStore } from "@/store/useAppStore";
import { supabase } from "@/lib/supabase";
import { Sparkles, CheckCircle } from "lucide-react";
import { Button } from "@/components/ui/button";

export default function Generating() {
    const navigate = useNavigate();
    const { sessionId, setGeneratedDoc } = useAppStore();
    const [progress, setProgress] = useState(0);
    const [status, setStatus] = useState("Initializing...");
    const [isComplete, setIsComplete] = useState(false);

    useEffect(() => {
        if (!sessionId) {
            navigate('/');
            return;
        }

        const generateDocs = async () => {
            try {
                // Progress simulation with status updates
                const steps = [
                    { progress: 10, status: "Loading configuration..." },
                    { progress: 25, status: "Processing analysis..." },
                    { progress: 40, status: "Generating structure..." },
                    { progress: 60, status: "Writing content..." },
                    { progress: 80, status: "Adding details..." },
                    { progress: 95, status: "Finalizing..." },
                ];

                // Call n8n generate webhook
                const webhookBase = import.meta.env.VITE_N8N_WEBHOOK_BASE;

                // Start progress animation
                let stepIndex = 0;
                const progressInterval = setInterval(() => {
                    if (stepIndex < steps.length) {
                        setProgress(steps[stepIndex].progress);
                        setStatus(steps[stepIndex].status);
                        stepIndex++;
                    }
                }, 1500);

                const response = await fetch(`${webhookBase}/generate`, {
                    method: 'POST',
                    headers: { 'Content-Type': 'application/json' },
                    body: JSON.stringify({ sessionId })
                });

                clearInterval(progressInterval);

                if (!response.ok) throw new Error('Generation failed');

                const result = await response.json();

                // Save to store
                if (result.markdown) {
                    setGeneratedDoc(result.markdown);
                }

                setProgress(100);
                setStatus("Complete!");
                setIsComplete(true);

            } catch (error) {
                console.error('Generation error:', error);
                // Fallback: Load from Supabase or use placeholder
                const { data } = await supabase
                    .from('documentation_sessions')
                    .select('final_markdown')
                    .eq('id', sessionId)
                    .single();

                if (data?.final_markdown) {
                    setGeneratedDoc(data.final_markdown);
                } else {
                    setGeneratedDoc(`# Project Documentation\n\nThis documentation was generated by DocuGithub.\n\n## Getting Started\n\nWelcome to your project documentation!\n\n## Installation\n\n\`\`\`bash\nnpm install\n\`\`\`\n\n## Usage\n\nDescribe how to use your project here.\n\n## Contributing\n\nContributions are welcome!\n\n## License\n\nMIT`);
                }

                setProgress(100);
                setStatus("Complete!");
                setIsComplete(true);
            }
        };

        generateDocs();
    }, [sessionId, navigate, setGeneratedDoc]);

    const handleContinue = () => {
        navigate('/editor');
    };

    return (
        <div className="min-h-screen flex items-center justify-center bg-background p-4">
            <div className="w-full max-w-md space-y-8 text-center">
                <div className="space-y-4">
                    <div className="relative inline-flex">
                        {isComplete ? (
                            <CheckCircle className="w-20 h-20 text-green-500" />
                        ) : (
                            <>
                                <Sparkles className="w-20 h-20 text-primary animate-pulse" />
                                <div className="absolute inset-0 flex items-center justify-center">
                                    <div className="w-24 h-24 border-4 border-primary/20 border-t-primary rounded-full animate-spin" />
                                </div>
                            </>
                        )}
                    </div>
                    <h1 className="text-3xl font-bold">
                        {isComplete ? "Documentation Ready!" : "Generating Documentation"}
                    </h1>
                    <p className="text-muted-foreground">{status}</p>
                </div>

                {/* Progress Bar */}
                <div className="space-y-2">
                    <div className="h-2 bg-muted rounded-full overflow-hidden">
                        <div
                            className="h-full bg-gradient-to-r from-primary to-primary/50 transition-all duration-500 ease-out"
                            style={{ width: `${progress}%` }}
                        />
                    </div>
                    <p className="text-sm text-muted-foreground">{progress}%</p>
                </div>

                {isComplete && (
                    <Button onClick={handleContinue} className="w-full h-12">
                        Open in Editor
                    </Button>
                )}
            </div>
        </div>
    );
}
